In [2]:
import numpy as np
m = [10,20,30,40,50]
marks = np.array(m)
marks = marks + 5
grade = marks>=45

s = marks.size

for i in range(s):
    print(marks[i]>=45)
    if marks[i]>=45 == True:
        print("Pass")
    else:
        print("Fail")

print(marks)
print(grade)


False
Fail
False
Fail
False
Fail
True
Fail
True
Fail
[15 25 35 45 55]
[False False False  True  True]


In [3]:
m = np.array([
    [85,78,90],
    [92,85,98],
    [76,82,80]
])
print("Python")
print(m[0,0])
print(m[1,0])
print(m[2,0])

print("Python-SQL")
print(m[0,0:2])
print(m[1,0:2])
print(m[2,0:2])

print("SQL-Excel")
print(m[0,1:3])
print(m[1,1:3])
print(m[2,1:3])

Python
85
92
76
Python-SQL
[85 78]
[92 85]
[76 82]
SQL-Excel
[78 90]
[85 98]
[82 80]


In [4]:
b1 = np.array([56,66,76])
b2 = np.array([46,86,96])

comb = np.concatenate((b1,b2))
print(comb)

print(np.split(comb,2))

for arr in np.split(comb,2):
    print(arr)

[56 66 76 46 86 96]
[array([56, 66, 76]), array([46, 86, 96])]
[56 66 76]
[46 86 96]


In [5]:
marka = np.array([[56,66,76],[46,86,96],[55,88,96]])
a = [1,2,3,4,5]
print([np.where(marka>=80)])

print(marka)

[(array([1, 1, 2, 2]), array([1, 2, 1, 2]))]
[[56 66 76]
 [46 86 96]
 [55 88 96]]


In [15]:
s = np.array(["Ram",45,True,False])
print(s)

n = type(s[2])
print(n)

['Ram' '45' 'True' 'False']
<class 'numpy.str_'>
